<a href="https://colab.research.google.com/github/Dan-Brooks/Programming-for-Data-Analysis-Cmet/blob/main/Data_Analysis_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Programming for Data Analysis** - CMP7005
This Project will analysis 4 weather monitoring stations

In [7]:
#Import Libraries
import pandas as pd
import numpy as np
import glob
import os
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns

The next step is to connect the Colab to the github an import the csv files

In [3]:
! git config --global user.name "Dan-Brooks"
! git config --global user.email "danielbrooks100@icloud.com"
username = "Dan-Brooks"
repo = "Programming-for-Data-Analysis-Cmet"
! git clone https://@github.com/{username}/{repo}

Cloning into 'Programming-for-Data-Analysis-Cmet'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 26 (delta 9), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (26/26), 3.31 MiB | 4.23 MiB/s, done.
Resolving deltas: 100% (9/9), done.

In [5]:
%cd {repo}

[Errno 2] No such file or directory: 'Programming-for-Data-Analysis-Cmet'
/content/Programming-for-Data-Analysis-Cmet
CMP7005_S2_PRAC1_Main_2025-26.pdf
Data_Analysis_Colab.ipynb
PRSA_Data_Changping_20130301-20170228.csv
PRSA_Data_Gucheng_20130301-20170228.csv
PRSA_Data_Huairou_20130301-20170228.csv
PRSA_Data_Nongzhanguan_20130301-20170228.csv
README.md

In [6]:
%ls

CMP7005_S2_PRAC1_Main_2025-26.pdf
Data_Analysis_Colab.ipynb
PRSA_Data_Changping_20130301-20170228.csv
PRSA_Data_Gucheng_20130301-20170228.csv
PRSA_Data_Huairou_20130301-20170228.csv
PRSA_Data_Nongzhanguan_20130301-20170228.csv
README.md

This Section Merges the CSV files

In [8]:
Air_Beijing = glob.glob("*.csv")
All_Air_Data = []
for filename in Air_Beijing:
    Air_df = pd.read_csv(filename)
    All_Air_Data.append(Air_df)
    print(f"Loaded: {filename}")
Com_Data = pd.concat(All_Air_Data, ignore_index=True)
Com_Data.to_csv("Air_Beijing_Combined.csv", index=False)
print(f"Combined {len(Air_Beijing)} files")
print(f"File rows {len(Com_Data)}")

Loaded: PRSA_Data_Changping_20130301-20170228.csv
Loaded: PRSA_Data_Gucheng_20130301-20170228.csv
Loaded: PRSA_Data_Nongzhanguan_20130301-20170228.csv
Loaded: PRSA_Data_Huairou_20130301-20170228.csv
Combined 4 files
File rows 140256

In [11]:
df = pd.read_csv("Air_Beijing_Combined.csv")
df.head()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,3.0,6.0,13.0,7.0,300.0,85.0,-2.3,1020.8,-19.7,0.0,E,0.5,Changping
1,2,2013,3,1,1,3.0,3.0,6.0,6.0,300.0,85.0,-2.5,1021.3,-19.0,0.0,ENE,0.7,Changping
2,3,2013,3,1,2,3.0,3.0,22.0,13.0,400.0,74.0,-3.0,1021.3,-19.9,0.0,ENE,0.2,Changping
3,4,2013,3,1,3,3.0,6.0,12.0,8.0,300.0,81.0,-3.6,1021.8,-19.1,0.0,NNE,1.0,Changping
4,5,2013,3,1,4,3.0,3.0,14.0,8.0,300.0,81.0,-3.5,1022.3,-19.4,0.0,N,2.1,Changping

In [12]:
df.tail()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
140251,35060,2017,2,28,19,16.0,28.0,2.0,19.0,300.0,95.0,9.9,1008.6,-14.1,0.0,WNW,1.8,Huairou
140252,35061,2017,2,28,20,21.0,34.0,4.0,24.0,500.0,80.0,9.5,1008.9,-14.4,0.0,SSW,1.3,Huairou
140253,35062,2017,2,28,21,17.0,33.0,2.0,39.0,900.0,60.0,8.4,1009.3,-14.6,0.0,SE,1.5,Huairou
140254,35063,2017,2,28,22,11.0,29.0,3.0,32.0,1400.0,69.0,8.3,1009.5,-14.7,0.0,ENE,3.2,Huairou
140255,35064,2017,2,28,23,11.0,20.0,2.0,27.0,400.0,77.0,6.7,1009.3,-13.6,0.0,NE,1.9,Huairou